### ISSUE TITLE
Save fails on HANA when tracking is enabled for Boolean fields 

### ISSUE THREAD

**Issue by dinurp** [cap-js/change-tracking#45]
Hi,

I get the following exception when I enabled change tracking for a Boolean field when using HANA db.

```
[cds] - Error: Cannot set parameter at row: 1. Argument must be a string
    at next (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:175:19)
    at ExecuteTask.getParameters (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:189:3)
    at ExecuteTask.sendExecute (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:196:8)
    at execute (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:73:10)
    at ExecuteTask.run (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:115:3)
    at run (/home/user/projects/testApp/node_modules/hdb/lib/util/Queue.js:97:12)
    at next (/home/user/projects/testApp/node_modules/hdb/lib/util/Queue.js:86:7)
    at done (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:53:5)
    at finalize (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:58:14)
    at execute (/home/user/projects/testApp/node_modules/hdb/lib/protocol/ExecuteTask.js:71:14) {
  query: 'INSERT INTO sap_changelog_Changes ( serviceEntityPath, entity, serviceEntity, attribute, valueChangedFrom, valueChangedTo, valueDataType, modification, keys, entityID, parentEntityID, parentKey, changeLog_ID, ID ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )',
  values: [
    [
      'my.Books(301)',
      'my.Books',
      'CatalogService.Books',
      'yesOrNo',
      '',
      true,
      'cds.Boolean',
      'update',
      'ID=301',
      '',
      '',
      '',
      '4eff86ee-c60f-4031-a64d-ef45db9f9aac',
      '08d9d030-46cb-433e-ac44-1ad660762bfc'
    ]
  ],
  numericSeverity: 4,
  id: '1989256',
  level: 'ERROR',
  timestamp: 1700054785696
}
```

Potential solution:
Please refer [here](https://github.com/cap-js/change-tracking/blob/main/lib/change-log.js#L290-L291). Values of `to` and `from`  are not ensured to be string. This is fine for sqlite. But Hana is not so forgiving. 

Regards,
Dinu

**Comment by nkaputnik** [comment]
Hello,
we have indentified this as a bug and will deliver a patch soon.

**Comment by nkaputnik** [comment]
Hello @dinurp 
the fix for this issue will be delivered with the next release, which should come next week...
