### ISSUE TITLE
Issue with numeric key format

### ISSUE THREAD

**Issue by SebSiegrist** [cap-js/change-tracking#74]
Hello,

I have activated change tracking with below version:
    "@cap-js/change-tracking": "^1.0.5",

And when activating the change tracking on an entity with numeric key I get following error during save.
The key of entity has integer64 format but the expected format should be a string in sap_changelog_ChangeLog.

`[cds] - Error: Cannot set parameter at row: 1. Argument must be a string
    at next (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/ExecuteTask.js:175:19)
    at ExecuteTask.getParameters (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/ExecuteTask.js:189:3)
    at ExecuteTask.sendExecute (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/ExecuteTask.js:196:8)
    at execute (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/ExecuteTask.js:73:10)
    at ExecuteTask.run (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/ExecuteTask.js:115:3)
    at run (/home/user/projects/MyWB/node_modules/hdb/lib/util/Queue.js:96:12)
    at next (/home/user/projects/MyWB/node_modules/hdb/lib/util/Queue.js:85:7)
    at receive (/home/user/projects/MyWB/node_modules/hdb/lib/util/Queue.js:114:5)
    at Connection.receive (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/Connection.js:385:3)
    at TLSSocket.ondata (/home/user/projects/MyWB/node_modules/hdb/lib/protocol/Connection.js:243:12) {
  query: 'INSERT INTO sap_changelog_ChangeLog ( entity, entityKey, serviceEntity, createdAt, createdBy, modifiedAt, modifiedBy, ID ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )',
  values: [
    [
      'my.db.Worklist',
      110026,`

Is there a possible correction or a workaround?

Thank you

**Comment by nkaputnik** [comment]
Hell @SebSiegrist 
the current implementation is assuming that you are using GUID as entity key, since this is also a pre-requisite to running Fiori Elements UI's with Draft enabled.
I am not aware of any workaround for this, since this pre-requisite is used ubiquitously in the code for expanding localized texts, so changing this would require a significant refactoring.

Best,
Nick
